filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      templates:
        - condition:
            contains:
              docker.container.name: "distributed-job-processor-app"
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
            # You can add more parse or multiline settings here if needed

    - type: docker
      hints.enabled: true
      templates:
        - condition:
            contains:
              docker.container.name: "distributed-job-processor-postgres"
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log

# -> logs to Elasticsearch
output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"]
  # If security is enabled, add username/password or token

# (Optional) console output for debugging
# output.console:
#   pretty: true
